config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  devise_for :users, path: 'users', controllers: { confirmations: "users/confirmations",
                                                   passwords: "users/passwords",
                                                   registrations: "users/registrations",
                                                   sessions: "users/sessions",
                                                   unlocks: "users/unlocks" }

  devise_for :organizations, path: 'organizations', controllers: { confirmations: "organizations/confirmations",
                                                                   passwords: "organizations/passwords",
                                                                   registrations: "organizations/registrations",
                                                                   sessions: "organizations/sessions",
                                                                   unlocks: "organizations/unlocks" }

  resources :projects do
    resources :bookings
  end

  resources :bookings, only: [] do
    member do
      get :accept
      get :decline
      get :concluded
      get :missed
    end
  end

  # User Routes

  resources :users, only: %i[show]

  get "users/:id/projects", to: "users#projects", as: "user_projects"

  get "users/:id/concluded", to: "users#concluded", as: "user_concluded"

  get "users/:id/skills", to: "users#skills", as: "user_skills"

  get "users/:id/badges", to: "users#badges", as: "user_badges"

  # Organization Routes

  resources :organizations, only: %i[show]

  get "organizations/:id/projects", to: "organizations#projects", as: "organization_projects"

  get "organizations/:id/concluded", to: "organizations#concluded", as: "organization_concluded"

  get "organizations/:id/requests", to: "organizations#requests", as: "organization_requests"

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
end

app/views/shared/_booking_attendance.html.erb
<div class="container attendance-div text-center my-5">
  <h3 class='my-4' id='attendance-title'><%= project.name %> attendance</h3>
  <div class="attendance-grid d-flex justify-content-between">
     <% project.bookings.each do |booking| %>
        <% if booking.status == 'accepted' || booking.status == 'concluded' || booking.status == 'missed' %>
          <div class="attendance-card d-flex flex-column align-items-center justify-content-center">
            <%= link_to user_path(booking.user), class:'attendance-avatar' do %>
              <% if booking.user.photo.attached? %>
                  <%= cl_image_tag booking.user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <% else %>
                <%= image_tag "https://icon-library.com/images/default-user-icon/default-user-icon-28.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <% end %>
            <% end %>
              <p>Did <strong><%= link_to booking.user.full_name, user_path(booking.user) %></strong><br>show up?</p>
            <% if booking.status == 'accepted' %>
              <div class="d-flex justify-content-center">
                <%= link_to concluded_booking_path(booking), data:{ turbo_confirm: 'Confirm this attendance?' } do %>
                  <i class="fa-solid fa-circle-check accept-booking mx-2"></i>
                <% end %>
                <%= link_to missed_booking_path(booking), data:{ turbo_confirm: 'Confirm this absence?' } do %>
                  <i class="fa-solid fa-x decline-booking"></i>
                <% end %>
              </div>
            <% else %>
              <div class="d-flex">
                <%= render 'shared/status', booking: booking %>
              </div>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_card.html.erb
<div class="card-project">
  <%= cl_image_tag  project.photos.first.key, crop: :fill, class: "project-image" %>

  <div class='d-flex flex-column'>
    <div class="card-project-infos ">
      <h2 class="mb-2"><%= project.name %></h2>
      <h3 class="mb-3"><i class="fa-solid fa-leaf"></i> <%= project.category %></h3>
      <p class="mb-2"><i class="fa-solid fa-location-dot"></i> <%= project.address %></p>
      <div class="d-flex mb-3">
        <p class="me-2"><i class="fa-solid fa-calendar-days"></i> <%= project.start_date.strftime("%d %b %Y") %></p>
        <p><i class="fa-solid ms-2 fa-calendar-check"></i> <%= project.end_date.strftime("%d %b %Y") %></p>
      </div>
      <p><%= project.description[0..120] %>...</p>
    </div>

    <% if project.end_date < Date.current && project.booking_status && project.organization == current_organization %>
      <div class="attendance">
        <%= link_to "Attendance Check", project_path(project), class: "btn attendance-button" %>
      </div>
    <% end %>
  </div>

  <div class="d-flex flex-column justify-content-between avatars">
    <div>
      <h4>Volunteers</h4>
      <div class="d-flex justify-content-start gap-2 flex-wrap">
        <% if project.bookings.empty? %>
        <p class="fs-6 btn-purple text-center py-2 px-4"><strong>Be the first to volunteer!</strong></p>
        <% else %>
          <% project.bookings.first(6).each do |booking|  %>
            <span class="vp" data-bs-placement="bottom" title= "<%= "#{booking.user.first_name} #{booking.user.last_name}"  %>" >
              <% if booking.user.photo.attached? %>
                <%= cl_image_tag booking.user.photo.key , crop: :fill, class:"avatar" %>
              <% else  %>
                <%= image_tag "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png", class:"avatar" %>
              <% end  %>
            </span>
          <% end  %>
        <% end %>
      </div>
    </div>


    <div>
      <h4 class="mt-3">Skills</h4>
      <div class="d-flex justify-content-around skills">
        <i class="fa-solid fa-hammer"></i>
        <i class="fa-sharp fa-solid fa-shield-dog"></i>
        <i class="fa-solid fa-paint-roller"></i>
      </div>
    </div>
  </div>
</div>
<script>
  const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
  const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
</script>

app/views/shared/_card_user_project.erb
<div class="card-user-project d-flex pe-0">
  <%= image_tag "https://images.unsplash.com/photo-1617450365226-9bf28c04e130?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80", class: "user-project-image b-radius" %>
  <div class="user-project-info d-flex flex-column justify-content-between p-3 w-100">
    <div>
      <div class="d-flex justify-content-between">
        <h4 class="mb-3"><%= project.name %></h4>
        <h4 class="d-flex align-items-center ms-4 mid-gray"><i class="fa-solid fa-hammer"></i></h4>
      </div>
      <p class="mb-3 mid-gray"><i class="fa-solid fa-location-dot mid-gray"></i> <%= project.city %> - <%= project.organization.country %></p>
      <div class="d-flex mid-gray">
        <p class="mb-4 me-4"><i class="fa-solid fa-calendar-days"></i> <%= project.start_date.strftime("%d %b %Y") %></p>
        <p><i class="fa-solid ms-2 fa-calendar-check"></i> <%= project.end_date.strftime("%d %b %Y") %></p>
      </div>
      <p class="mb-2 mid-gray"><%= project.description[0..120] %>...</p>
    </div>
    <div class="d-flex">
      <span class="status-pending mt-3 mb-0 py-1 px-4 b-solid b-radius">Pending</span>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<section id="footer" class="p-5">
  <div class="footer-info text-center p-5">
    <div class="d-flex justify-content-around my-4 gap-2">
      <%= link_to "Home", root_path, class: "fs-6" %>
      <%= link_to "About", '/#about', class: "fs-6" %>
      <%= link_to "Projects", projects_path, class: "fs-6" %>
    </div>
    <div class="d-flex justify-content-around my-4">
      <a href=""><i class="footer-icon fa-brands fa-twitter"></i></a>
      <a href=""><i class="footer-icon fa-brands fa-facebook-f"></i></a>
      <a href=""><i class="footer-icon fa-brands fa-instagram"></i></a>
      <a href=""><i class="footer-icon fa-solid fa-envelope"></i></a>
    </div>
    <p>2022 © Karuna</p>
  </div>
</section>

app/views/shared/_map.html.erb
<svg version="1.0" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 468 239"
preserveAspectRatio="xMidYMid meet">
 <!--adicionar no url a query string -->


<a xlink:title='Africa' href='/projects?continent=africa'>
  <%= display_africa %>
</a>

<a xlink:title='Asia' href='/projects?continent=asia'>
  <%= display_asia %>
</a>

<a xlink:title='Oceania' href='/projects?continent=oceania'>
  <%= display_oceania %>
</a>

<a xlink:title='Europe' href='/projects?continent=europe'>
  <%= display_europe %>
</a>

<a xlink:title='South America' href='/projects?continent=south america'>
  <%= display_south_america %>
</a>

<a xlink:title='North America' href='/projects?continent=north america'>
  <%= display_north_america %>
</a>
</svg>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-lewagon">
  <div class="container-fluid">
    <div class="d-flex align-items-center">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "https://cdn-icons-png.flaticon.com/512/5168/5168452.png" %>
      <% end %>
      <%= link_to root_path do %>
        <h2 class="navbar-title font-weight-bold m-0">Karuna</h2>
      <% end %>
    </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "About us", '/#about', class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Projects", projects_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <% if current_user.photo.key %>

              <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
             <%= image_tag ("https://w7.pngwing.com/pngs/754/2/png-transparent-samsung-galaxy-a8-a8-user-login-telephone-avatar-pawn-blue-angle-sphere-thumbnail.png"), class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>

            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>

          </li>
        <% elsif organization_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "About us", '/#about', class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Projects", projects_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My panel", organization_path(current_organization), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "New project", new_project_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <%= cl_image_tag current_organization.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My panel", organization_path(current_organization), class: "dropdown-item" %>
              <%= link_to "New project", new_project_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_organization_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "About us", '/#about', class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Donate", '/', class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Become a partner", new_organization_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-button ms-3">
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link btn-white" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>
<%= image_tag 'main-wave.png', id:'navbar-wave' %>

app/views/shared/_organization_about.html.erb
<div class="container d-flex justify-content-center my-4">
  <div class="row justify-content-center">
    <div class="col-12 col-lg-5 my-3">
      <h4 class="fw-bold mb-4">About</h4>
      <p class="mb-3">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean etiam consectetur arcu etiam quis aliquam tortor tincidunt. Placerat scelerisque nisl ultrices arcu etiam.</p>
      <p class="text-muted"><i class="fa-solid fa-location-dot"></i> <%= @organization.address %> - <%= @organization.country %></p>
    </div>

    <div class="col-12 col-lg-5 my-3">
      <h4 class="fw-bold mb-4">Projects</h4>
      <div class="d-flex gap-4">
        <div class="card-round rounded-circle bg-primary text-success text-center d-flex flex-column justify-content-center pb-1">
          <p class="fs-4 fw-bold lh-1 m-0">5</p>
          <p class="m-0">Active</p>
        </div>
        <div class="card-round rounded-circle bg-primary text-success text-center d-flex flex-column justify-content-center pb-1">
          <p class="fs-4 fw-bold lh-1 m-0">1</p>
          <p class="m-0">Ongoing</p>
        </div>
        <div class="card-round rounded-circle bg-primary text-success text-center d-flex flex-column justify-content-center pb-1">
          <p class="fs-4 fw-bold lh-1 m-0">16</p>
          <p class="m-0">Concluded</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_status.html.erb
<% case booking.status %>
  <% when 'pending' %>
    <span class="status-pending mb-0 py-1 px-4 b-solid b-radius">Pending</span>
  <% when 'accepted' %>
    <span class="status-accepted mb-0 py-1 px-4 b-solid b-radius">Accepted</span>
  <% when 'declined' %>
    <span class="status-declined mb-0 py-1 px-4 b-solid b-radius">Declined</span>
  <% when 'concluded' %>
    <span class="status-concluded mb-0 py-1 px-4 b-solid b-radius">Concluded</span>
  <% when 'missed' %>
    <span class="status-missed mb-0 py-1 px-4 b-solid b-radius">Missed</span>
<% end %>

app/views/shared/_tabs.html.erb
<div class="tabs d-flex justify-content-center align-items-end pb-0">
  <% if @user %>
    <%= link_to user_projects_path, class: "tab-link mt-4 pb-0 mb-0 active", data: { action: "click->user-tabs#renderProjects", user_tabs_target: "projects" } do %>
      <p class="pb-3 mb-0">Projects</p>
    <% end %>
    <%= link_to user_concluded_path, class: "tab-link mt-4 pb-0 mb-0", data: { action: "click->user-tabs#renderConcluded", user_tabs_target: "concluded" } do %>
      <p class="pb-3 mb-0">Concluded</p>
    <% end %>
    <%= link_to user_skills_path, class: "tab-link mt-4 pb-0 mb-0 d-none", data: { action: "click->user-tabs#renderSkills", user_tabs_target: "skills" } do %>
      <p class="pb-3 mb-0">Skills</p>
    <% end %>
    <%= link_to user_badges_path, class: "tab-link mt-4 pb-0 mb-0 d-none", data: { action: "click->user-tabs#renderBadges", user_tabs_target: "badges" } do %>
      <p class="pb-3 mb-0">Badges</p>
    <% end %>
  <% end %>

  <% if @organization %>
    <%= link_to organization_projects_path, class: "tab-link mt-4 pb-0 mb-0 active", data: { action: "click->organization-tabs#renderProjects", organization_tabs_target: "projects" } do %>
      <p class="pb-3 mb-0">Projects</p>
    <% end %>
    <%= link_to organization_concluded_path, class: "tab-link mt-4 pb-0 mb-0", data: { action: "click->organization-tabs#renderConcluded", organization_tabs_target: "concluded" } do %>
      <p class="pb-3 mb-0">Concluded</p>
    <% end %>
    <% if @organization == current_organization %>
      <%= link_to organization_requests_path, class: "tab-link mt-4 pb-0 mb-0", data: { action: "click->organization-tabs#renderRequests", organization_tabs_target: "requests" } do %>
        <p class="pb-3 mb-0">Requests</p>
      <% end %>
    <% else %>
      <%= link_to organization_requests_path, class: "tab-link mt-4 pb-0 mb-0 d-none", data: { action: "click->organization-tabs#renderRequests", organization_tabs_target: "requests" } do %>
        <p class="pb-3 mb-0">Requests</p>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/shared/_user_cards.html.erb
<% @user.projects.each do |project| %>
  <% if project.end_date > Date.current%>
    <div class="mb-5">
      <%= link_to project_path(project), class: "hover-purple text-decoration-none" do %>
        <%= render 'shared/user_project_card', project: project, booking: project.bookings.find_by(user: @user) %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/shared/_user_concluded.html.erb
<% @user.projects.each do |project| %>
  <% if project.end_date < Date.current%>
    <div class="mb-5">
      <%= link_to project_path(project), class: "hover-purple text-decoration-none" do %>
        <%= render 'shared/user_project_card', project: project, booking: project.bookings.find_by(user: @user) %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/shared/_user_panel.html.erb
<div class="user-panel-aside d-flex">
  <% if @user.photo.attached? %>
    <%= cl_image_tag @user.photo.key, class: "avatar-xl mb-3" %>
  <% else  %>
    <%= image_tag("https://w7.pngwing.com/pngs/754/2/png-transparent-samsung-galaxy-a8-a8-user-login-telephone-avatar-pawn-blue-angle-sphere-thumbnail.png", class: "avatar-xl mb-3") %>
  <% end %>
  <div class="user-bio" data-controller="modal">
    <h3><%= @user.first_name%> <%= @user.last_name %></h3>
    <p class="mb-2"><%= @user.about %></p>
    <p class="text-info fs-sm"><i class="fa-solid fa-location-dot"></i> <%= @user.country %></p>
    <% if @user.status_count.count('concluded') > 0 %>
    <div class="b-bottom my-2"></div>
      <%= button_tag data: { action: "click->modal#openMedalModal" } do  %>
        <%= image_tag "https://cdn-icons-png.flaticon.com/512/4168/4168977.png", class: "user-medal" %>
      <% end %>
    <% end %>

    <div class="modal" data-modal-target="medalModal">
      <div class="modal-content">
        <div class="modal-header">
          <button data-action="click->modal#closeMedalModal">&times;</button>
          <h3>Amazing! 🎉</h3>
        </div>
        <div class="modal-body text-center">
          <p><strong><%= @user.full_name %></strong> concluded a Project!</p>
          <%= image_tag "https://media2.giphy.com/media/MeIucAjPKoA120R7sN/giphy.gif?cid=ecf05e474wsbdsa8eyp46ydzbwnr23qg2fj3u1dah1ppmn98&rid=giphy.gif&ct=g", class: "medal-animation"  %>
        </div>
      </div>
    </div>

    <% if @user.status_count.count('concluded') > 4 %>
      <%= button_tag data: { action: "click->modal#openSecondMedalModal" } do  %>
        <%= image_tag "https://cdn-icons-png.flaticon.com/512/8289/8289880.png", class: "user-medal"  %>
      <% end %>
    <% end %>
    <div class="modal" data-modal-target="secondMedalModal">
      <div class="modal-content">
        <div class="modal-header">
          <button data-action="click->modal#closeSecondMedalModal">&times;</button>
          <h3>Wow!! 😯</h3>
        </div>
        <div class="modal-body text-center">
          <p><strong><%= @user.full_name %></strong> made impact on 5 different projects!</p>
          <%= image_tag "https://media4.giphy.com/media/OSOOHw7N9gb3R06OU7/giphy.gif?cid=ecf05e477dsxasztv79lf7xgheb1qisfqnmkllll6ejaks1l&rid=giphy.gif&ct=g", class: "medal-animation"  %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_user_project_card.html.erb
<div class="user-project-card d-flex pe-0">

  <%= cl_image_tag project.photos.first.key, crop: :fill, class: "user-project-image b-radius" %>
  <div class="user-project-info d-flex flex-column justify-content-between p-3 w-100">
    <div>
      <div class="d-flex justify-content-between">
        <h4 class="mb-3"><%= project.name %></h4>
        <h4 class="d-flex align-items-center ms-4 mid-gray"><i class="fa-solid fa-hammer"></i></h4>
      </div>
      <p class="mb-3 mid-gray"><i class="fa-solid fa-location-dot mid-gray"></i> <%= project.city %> - <%= project.organization.country %></p>
      <div class="d-flex mid-gray">
        <p class="mb-4 me-4"><i class="fa-solid fa-calendar-days"></i> <%= project.start_date.strftime("%d %b %Y") %></p>
        <p><i class="fa-solid ms-2 fa-calendar-check"></i> <%= project.end_date.strftime("%d %b %Y") %></p>
      </div>
      <p class="mb-2 mid-gray"><%= project.description[0..120] %>...</p>
    </div>
    <div class="d-flex mt-3">
      <%= render 'shared/status', booking: booking %>
    </div>
  </div>
</div>