config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  devise_for :users, path: 'users', controllers: { confirmations: "users/confirmations",
                                                   passwords: "users/passwords",
                                                   registrations: "users/registrations",
                                                   sessions: "users/sessions",
                                                   unlocks: "users/unlocks" }

  devise_for :organizations, path: 'organizations', controllers: { confirmations: "organizations/confirmations",
                                                                   passwords: "organizations/passwords",
                                                                   registrations: "organizations/registrations",
                                                                   sessions: "organizations/sessions",
                                                                   unlocks: "organizations/unlocks" }

  resources :projects do
    resources :bookings
  end

  resources :bookings, only: [] do
    member do
      get :accept
      get :decline
      get :concluded
      get :missed
    end
  end

  # User Routes

  resources :users, only: %i[show]

  get "users/:id/projects", to: "users#projects", as: "user_projects"

  get "users/:id/concluded", to: "users#concluded", as: "user_concluded"

  get "users/:id/skills", to: "users#skills", as: "user_skills"

  get "users/:id/badges", to: "users#badges", as: "user_badges"

  # Organization Routes

  resources :organizations, only: %i[show]

  get "organizations/:id/projects", to: "organizations#projects", as: "organization_projects"

  get "organizations/:id/concluded", to: "organizations#concluded", as: "organization_concluded"

  get "organizations/:id/requests", to: "organizations#requests", as: "organization_requests"

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
end

app/models/project.rb
class Project < ApplicationRecord
  after_create :set_default_image

  belongs_to :organization
  has_many :bookings
  has_one :chatroom
  after_create :set_chatroom
  has_many_attached :photos

  CATEGORIES = %w[Agriculture Animal\ Rescue Construction Education Environmental Relief\ Effort Sanitation Water\ Access]

  validates :category, inclusion: { in: CATEGORIES }
  validates :available_spots, numericality: { greater_than: 0 }

  include PgSearch::Model
  pg_search_scope :search_by_category,
                  against: [:category],
                  using: {
                  tsearch: { prefix: true }
                  }

  pg_search_scope :search_by_continent,
                  against: [:continent],
                  using: {
                    tsearch: { prefix: true }
                  }

  pg_search_scope :search_by_project,
  against: [ :name, :description, :category, :address, :city ],
  using: {
    tsearch: { prefix: true }
  }

  def booking_status
    bookings_status = self.bookings.map do |booking|
                        booking.status
                      end
    bookings_status.include?('accepted')
  end

  private

  def set_chatroom
    @chatroom = Chatroom.new(name: self.name)
    @chatroom.project = self
    @chatroom.save!
  end

  def set_default_image
    if self.photos.empty?
      self.photos.attach(io: File.open(Rails.root.join('app/assets/images/project_default_photo.jpg')),
      filename: 'project_default_photo.jpg')
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = policy_scope(Project)
    # @projects.search_by_category(params[:category])
    if params[:category].present?
      @projects = policy_scope(Project).search_by_category(params[:category])
    elsif params[:continent].present?
      @projects = policy_scope(Project).search_by_continent(params[:continent])
    elsif params[:query].present?
      @projects = policy_scope(Project).search_by_project(params[:query])
    end
    respond_to do |format|
      format.html # Follow regular flow of Rails
      format.text { render partial: "projects/list", locals: {projects: @projects}, formats: [:html] }
    end
  end

  def show
    authorize @project
    @booking = Booking.new
    authorize @booking
    @chatroom = @project.chatroom
  end

  def new
    @project = Project.new
    authorize @project
  end

  def create
    @project = Project.new(project_params)
    @project.organization = current_organization

    authorize @project
    if @project.save
      redirect_to @project, notice: "Project was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize @project
  end

  def update
    authorize @project
    @project.update(project_params_edit)
    redirect_to organization_path(current_organization)
  end

  def destroy
    authorize @project

    @project.destroy
    redirect_to organization_path(current_organization), notice: "Project was successfully deleted.", status: :see_other
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name,
                                    :description,
                                    :category,
                                    :address,
                                    :city,
                                    :continent,
                                    :available_spots,
                                    :start_date,
                                    :end_date,
                                    photos: []
                                   )
  end

  def project_params_edit
    params.require(:project).permit(:name,
                                    :description,
                                    :category,
                                    :address,
                                    :city,
                                    :continent,
                                    :available_spots,
                                    :start_date,
                                    :end_date
                                   )
  end
end

app/views/projects/_list.html.erb
<div data-search-target="list" class="row justify-content-center">
  <% @projects.each do |project| %>
    <% if project.end_date > Date.current%>
      <div class="col-11 col-md-10 pt-5">
        <%= link_to project_path(project), class: "hover-purple text-decoration-none" do %>
          <%= render 'shared/card', project: project %>
        <% end %>
      </div>
    <% end %>
  <% end %>


</div>

app/views/projects/edit.html.erb
<% categories = %w[Agriculture Animal\ Rescue Construction Education Environmental Relief\ Effort Sanitation Water\ Access] %>

<main class="container my-5 p-5">
  <div class="form-card background-purple b-radius p-5">
    <h1 class="mb-4">Edit your Project</h1>
    <%= simple_form_for @project, data: { controller: "flatpickr" } do |f| %>
      <%= f.input :name, label: "Project name", input_html: { class: "border-purple b-radius px-4" } %>
      <%= f.input :description, input_html: { class: "border-purple b-radius px-4" } %>
      <%= f.input :category, collection: categories, input_html: { class: "border-purple b-radius px-4" } %>
      <%= f.input :address, input_html: { class: "border-purple b-radius px-4" } %>
      <%= f.input :city, input_html: { class: "border-purple b-radius px-4" } %>
      <%= f.input :available_spots, input_html: { class: "border-purple b-radius px-4", min: '1' } %>
      <%= f.input :start_date, input_html: { class: "border-purple b-radius px-4", data: { flatpickr_target: "firstRangeInput" }, value: @project.start_date.strftime("%d %b, %Y") }, as: :string %>
      <%= f.input :end_date, input_html: { class: "border-purple b-radius px-4", data: { flatpickr_target: "secondRangeInput" }, value: @project.end_date.strftime("%d %b, %Y")  }, as: :string %>
      <%= f.submit class: "btn btn-lg btn-outline-light b-radius w-100 mt-3" %>
    <% end %>
  </div>
</main>

app/views/projects/index.html.erb
<main class="p-5">
  <div data-controller="search", class="container mx-auto">

    <div data-project-card-target="content" class="row mt-3 justify-content-center project-cards ">
        <%= form_with url: projects_path, method: :get, html: {class: "d-flex project-index-form mt-5", data: {search_target: "form"}} do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control project-index-search-input",
            placeholder: "Find a project",
            data: {search_target: "input",
            action: "keyup->search#update"} %>
          <%= submit_tag "Search", class: "btn btn-primary project-index-submit" %>
        <% end %>
        <%= render "projects/list" %>
      </div>
    </div>
  </div>
</main>

app/views/projects/new.html.erb
<% categories = %w[Agriculture Animal\ Rescue Construction Education Environmental Relief\ Effort Sanitation Water\ Access] %>
<% continents = %w[Africa Asia Europe North\ America South\ America Oceania ] %>

<main class="container my-5 p-5">
  <div class="form-card background-purple b-radius p-5">
    <h1 class="mb-4">Create your Project</h1>
    <%= simple_form_for @project, data: { controller: "flatpickr" } do |f| %>
      <%= f.input :name, label: "Project name", input_html: { class: "border-purple b-radius px-4" } %>
      <%= f.input :description, input_html: { class: "border-purple b-radius px-4" } %>
      <%= f.input :category, collection: categories, input_html: { class: "border-purple b-radius px-4" } %>
      <%= f.input :address, input_html: { class: "border-purple b-radius px-4" } %>
      <%= f.input :city, input_html: { class: "border-purple b-radius px-4" } %>
      <%= f.input :continent, collection: continents, input_html: { class: "border-purple b-radius px-4" } %>
      <%= f.input :available_spots, input_html: { class: "border-purple b-radius px-4", min: '1' } %>
      <%= f.input :start_date, input_html: { class: "border-purple b-radius px-4", data: { flatpickr_target: "firstRangeInput" } }, as: :string %>
      <%= f.input :end_date, input_html: { class: "border-purple b-radius px-4", data: { flatpickr_target: "secondRangeInput" }  }, as: :string %>
      <%= f.input :photos, as: :file, input_html: { multiple: true, class: "border-purple b-radius px-4" } %>
      <%= f.submit class: "btn btn-lg btn-outline-light b-radius w-100 mt-3" %>
    <% end %>
  </div>
</main>

app/views/projects/show.html.erb
<% content_for :meta_title, "#{@project.name} · #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @project.description %>
<%# content_for :meta_image, cl_image_path(@project.photos.first.key) %>

<div class="container showpage-title mb-3">
  <h1 class= "project-header ms-0"><strong> <%= @project.name %></strong></h1>
</div>

<div class="container">
  <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <% @project.photos.each_with_index do |photo, index| %>
        <% if index == 0 %>
          <div class="carousel-item active">
            <%= cl_image_tag photo.key, crop: :fill, class:"d-block w-100" %>
          </div>
        <% else %>
          <div class="carousel-item">
            <%= cl_image_tag photo.key, crop: :fill, class:"d-block w-100" %>
          </div>
        <% end %>
      <% end %>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</div>

<div class="container project-infos">
  <div class="row">
    <div class="col col-9">
      <h2><i class="fa-solid fa-leaf me-3 ms-2 mt-4"></i><strong><%= @project.category %></strong></h2>
    </div>
    <div class="col col-3", style="align-self: center; font-weight: bold; bs-link-hover-color: purple;" >
      <%= link_to "Visit #{@project.organization.name} Page", organization_path(@project.organization_id) %>
    </div>
  </div>
  <p style="color:grey;"><i class="fa-solid fa-location-dot ms-2 mt-3"></i> <%= @project.address %></p>
  <p style="color:grey;"><i class="fa-solid fa-calendar-days ms-2"></i>  <%= @project.start_date %> <i class="fa-solid fa-calendar-check ms-4"></i>  <%= @project.end_date %></p>
  <p class="text-justify ms-2 p-description mt-4"> <%= @project.description %> </p>
</div>


<% if organization_signed_in? && @project.organization == current_organization && @project.end_date < Date.current %>
  <%= render 'shared/booking_attendance', project: @project %>
<% else %>
  <div class="container project-volunteers mt-5">
    <h3>Volunteers</strong></h3>
    <div class="volunteer-grid d-flex justify-content-between">
      <% @project.bookings.each do |booking|  %>
        <span class="vp" data-bs-placement="bottom" title= "<%= "#{booking.user.first_name} #{booking.user.last_name}"  %>" >
          <%= link_to user_path(booking.user) do %>
            <% if booking.user.photo.attached? %>
              <%= cl_image_tag booking.user.photo.key , crop: :fill, class:"volunteer-pics mx-2" %>
            <% else  %>
              <%= image_tag "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png", class:"volunteer-pics" %>
            <% end  %>
          <% end %>
        </span>
      <% end  %>
    </div>
  </div>
<% end %>

<% if (user_signed_in? || organization_signed_in?) && policy(@chatroom).show? %>
    <div class="container mb-5 d-flex justify-content-center">
      <div class="d-flex flex-column align-items-center text-center justify-content-around chatroom-div">
        <% if user_signed_in? %>
          <h2>You're already part of this family!<br>Wanna share something? </h2>
        <% elsif organization_signed_in? %>
          <h2>Something important to discuss with your team?</h2>
        <% end %>
        <%= link_to "JOIN THE CHAT", chatroom_path(@chatroom), class:'btn btn-purple w-50' %>
      </div>
    </div>
<% elsif !organization_signed_in? %>
  <div class="container mb-5">
    <div class="d-flex justify-content-center">
      <section id="bookings" class="background my-5">
        <div class="offer-info container p-5 border form-show-page">
          <h3 class="text-center mb-3">Join the team</h3>
          <%= simple_form_for [@project, @booking], data: { controller: "flatpickr" } do |f| %>
            <%= f.input :start_date, label: false, placeholder: 'Start date', input_html: { class: "border-green b-radius my-5", data: { flatpickr_target: "firstRangeInput" } }, as: :string %>
            <%= f.input :end_date, label: false, placeholder: 'End date', input_html: { class: "border-green b-radius mb-4", data: { flatpickr_target: "secondRangeInput" } }, as: :string %>
            <%= f.submit "Volunteer", class: "btn btn-lg btn-block btn-purple w-100 mt-4" %>
          <% end %>
        </div>
      </section>
    </div>
  </div>
<% end %>
<script>
  const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
  const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
</script>