config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  devise_for :users, path: 'users', controllers: { confirmations: "users/confirmations",
                                                   passwords: "users/passwords",
                                                   registrations: "users/registrations",
                                                   sessions: "users/sessions",
                                                   unlocks: "users/unlocks" }

  devise_for :organizations, path: 'organizations', controllers: { confirmations: "organizations/confirmations",
                                                                   passwords: "organizations/passwords",
                                                                   registrations: "organizations/registrations",
                                                                   sessions: "organizations/sessions",
                                                                   unlocks: "organizations/unlocks" }

  resources :projects do
    resources :bookings
  end

  resources :bookings, only: [] do
    member do
      get :accept
      get :decline
      get :concluded
      get :missed
    end
  end

  # User Routes

  resources :users, only: %i[show]

  get "users/:id/projects", to: "users#projects", as: "user_projects"

  get "users/:id/concluded", to: "users#concluded", as: "user_concluded"

  get "users/:id/skills", to: "users#skills", as: "user_skills"

  get "users/:id/badges", to: "users#badges", as: "user_badges"

  # Organization Routes

  resources :organizations, only: %i[show]

  get "organizations/:id/projects", to: "organizations#projects", as: "organization_projects"

  get "organizations/:id/concluded", to: "organizations#concluded", as: "organization_concluded"

  get "organizations/:id/requests", to: "organizations#requests", as: "organization_requests"

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
end

app/models/organization.rb
class Organization < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  after_create :set_default_image

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :projects
  has_many :bookings, through: :projects
  has_many :messages
  has_one_attached :photo

  private

  def set_default_image
    unless self.photo.attached?
      self.photo.attach(io: File.open(Rails.root.join('app/assets/images/org_default_photo.jpg')),
      filename: 'org_default_photo.jpg')
    end
  end
end

app/controllers/organizations/confirmations_controller.rb
# frozen_string_literal: true

class Organizations::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/organizations/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Organizations::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/organizations/passwords_controller.rb
# frozen_string_literal: true

class Organizations::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/organizations/registrations_controller.rb
# frozen_string_literal: true

class Organizations::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]
  include Accessible
  skip_before_action :check_user, only: %i[edit update destroy cancel]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name address country website about])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name address country website about])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/organizations/sessions_controller.rb
# frozen_string_literal: true

class Organizations::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]
  include Accessible
  skip_before_action :check_user, only: :destroy

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: %i[name address country website about])
  end
end

app/controllers/organizations/unlocks_controller.rb
# frozen_string_literal: true

class Organizations::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: %i[show projects concluded requests]

  def show
    authorize @organization
  end

  def projects
    authorize @organization
    render_partial("project_cards")
  end

  def concluded
    # @projects = @organization.projects.where("end_date < ?", "#{Date.current}")
    authorize @organization
    render_partial("concluded")
  end

  def requests
    authorize @organization
    render_partial("requests")
  end

  private

  def render_partial(content)
    respond_to do |format|
      format.html
      format.text { render partial: "organizations/organization_#{content}", locals: { organization: @organization }, formats: [:html] }
    end
  end

  def other_or_no_organization
    @organization != current_organization || current_organization.nil?
  end

  def set_organization
    if other_or_no_organization
      @organization = Organization.find_by(id: params[:id])
    elsif current_organization
      @organization = current_organization
    end
    redirect_to root_path if @organization.nil?
  end
end

app/views/organizations/_organization_about.html.erb
<div class="container d-flex justify-content-center my-4">
  <div class="row justify-content-center">

    <div class="col-12 col-lg-5 my-3">
      <h4 class="fw-bold mb-4">About</h4>
      <p class="mb-3"><%= @organization.about %></p>
      <p class="text-muted"><i class="fa-solid fa-location-dot"></i> <%= @organization.address %> - <%= @organization.country %></p>
    </div>

    <div class="col-12 col-lg-5 my-3">
      <h4 class="fw-bold mb-4">Projects</h4>
      <div class="d-flex gap-4">
        <div class="card-round rounded-circle bg-primary text-success text-center d-flex flex-column justify-content-center pb-1">
          <p class="fs-4 fw-bold lh-1 m-0"><%= @organization.projects.where("end_date > ?", "#{Date.current}").length %></p>
          <p class="m-0">Active</p>
        </div>
        <div class="card-round rounded-circle bg-primary text-success text-center d-flex flex-column justify-content-center pb-1">
          <p class="fs-4 fw-bold lh-1 m-0">0</p>
          <p class="m-0">Ongoing</p>
        </div>
        <div class="card-round rounded-circle bg-primary text-success text-center d-flex flex-column justify-content-center pb-1">
          <p class="fs-4 fw-bold lh-1 m-0"><%= @organization.projects.where("end_date < ?", "#{Date.current}").length %></p>
          <p class="m-0">Concluded</p>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/organizations/_organization_banner.html.erb
<div class="banner-organization"
  style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url('<%= cl_image_path organization.photo.key, crop: :fill %>')">
  <div class="container d-flex flex-column justify-content-center align-items-center h-100 gap-4">
    <h1 class="text-success fs-lg fw-bold"><%= @organization.name %></h1>
  </div>
</div>

app/views/organizations/_organization_concluded.html.erb
<div class="container mx-auto">
  <div class="row justify-content-center project-cards gap-5">
    <% @organization.projects.each do |project| %>
      <% if project.end_date < Date.current%>
        <div class="col-11 col-md-10">
          <%= link_to project_path(project), class: "hover-purple text-decoration-none" do %>
            <%= render 'shared/card', project: project %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/organizations/_organization_project_cards.html.erb
<div class="container mx-auto">
  <div class="row justify-content-center project-cards gap-5">
    <% @organization.projects.each do |project| %>
      <% if project.end_date > Date.current%>
        <div class="col-11 col-md-10">
          <%= link_to project_path(project), class: "hover-purple text-decoration-none" do %>
            <div class="d-flex">
              <%= render 'shared/card', project: project %>
              <% if policy(project).edit? %>
                <%=  link_to edit_project_path(project) do %>
                  <div class="container">
                    <i class="fa-regular fa-pen-to-square"></i>
                  </div>
                <% end %>
              <% end %>
              <% if policy(project).destroy? %>
                <%=  link_to project_path(project), data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this project?"} do %>
                  <i class="fa-solid fa-trash"></i>
                <% end %>
              <% end %>
              <!-- app/views/restaurants/show.html.erb -->
            </div>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/organizations/_organization_project_concluded.html.erb
<div class="container mx-auto">
  <div class="row justify-content-center project-cards gap-5">
    <% @organization.projects.each do |project| %>
      <% if project.end_date > Date.current%>
        <div class="col-11 col-md-10">
          <%= link_to project_path(project), class: "hover-purple text-decoration-none" do %>
            <%= render 'shared/card', project: project %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/organizations/_organization_requests.html.erb
<div class="container">
  <% @organization.projects.each do |project| %>
    <% if project.bookings.present? %>
      <% project.bookings.each do |booking| %>
        <div class="container project-card-request d-flex">
          <%= cl_image_tag  project.photos.first.key, crop: :fill, class: "request-picture" %>
          <div class="request-card-info">
            <h2><%= project.name %></h2>
              <p><strong><%= link_to "#{booking.user.full_name}", user_path(booking.user) %></strong> wants to volunteer on your <%= booking.project.category %> project from <%= booking.start_date.strftime('%d %b %Y') %> to <%= booking.end_date.strftime('%d %b %Y') %>.</p>
              <% if booking.status == 'pending' %>
                <div class="d-flex justify-content-end">
                  <%= link_to accept_booking_path(booking) do %>
                    <i class="fa-solid fa-circle-check accept-booking mx-2"></i>
                  <% end %>
                  <%= link_to decline_booking_path(booking) do %>
                    <i class="fa-solid fa-x decline-booking"></i>
                  <% end %>
                </div>
              <% else %>
                <div class="d-flex justify-content-end">
                    <%= render 'shared/status', booking: booking %>
                </div>
              <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/organizations/show.html.erb
<% content_for :meta_title, "#{@organization.name} · #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @organization.about %>
<%# content_for :meta_image, cl_image_path(@organization.photo.key) %>

<div data-controller="organization-tabs">
  <header>
    <%= render 'organizations/organization_banner', organization: @organization %>

    <%= render 'organizations/organization_about', organization: @organization %>

    <nav class="b-bottom w-100 mt-2 pb-0">
      <%= render 'shared/tabs' %>
    </nav>
  </header>

  <main data-organization-tabs-target="main" class="mt-2 mb-5 p-5">
    <%= render 'organizations/organization_project_cards', organization: @organization %>
  </main>
</div>